

#define NAND2TETRIS_ADD_VAR(name) name,
#define NAND2TETRIS_GET_VAR_VAR(name) name

typedef enum {
    #include "variables.h"
    NAND2TETRIS_VAR_COUNT, 
} NAND2TETRIS_VARS;

NAND2TETRIS_ADD_VAR(R0)
NAND2TETRIS_ADD_VAR(R1)
NAND2TETRIS_ADD_VAR(R2)
NAND2TETRIS_ADD_VAR(R3)
NAND2TETRIS_ADD_VAR(R4)
NAND2TETRIS_ADD_VAR(R5)
NAND2TETRIS_ADD_VAR(R6)
NAND2TETRIS_ADD_VAR(R7)
NAND2TETRIS_ADD_VAR(R9)
NAND2TETRIS_ADD_VAR(R9)
NAND2TETRIS_ADD_VAR(R10)
NAND2TETRIS_ADD_VAR(R11)
NAND2TETRIS_ADD_VAR(R12)
NAND2TETRIS_ADD_VAR(R13)
NAND2TETRIS_ADD_VAR(R14)
